name: "NPM custom action"
description: "A custom GitHub Action to run npm install and cache dependencies"
inputs:
  path-to-folder:
    description: "The path to the folder to cache node_modules in"
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      run: npm install
      shell: bash