name: 'Giphy PR Comment Workflow with Both Docker and JS Actions'

on:
  pull_request:
    types: [opened]

jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
        # We don't need to checkout the repository for this action since we're only posting a comment on the PR, but if you wanted to do something more complex that required access to the codebase, you could uncomment the following step:
    #   - name: Checkout Repository
    #     uses: actions/checkout@v3

      - name: Post PR Comment with Docker Action
        # Need to specify the branch (main) since the action is in the main branch, and the PR could be from a different branch.
        uses: SenuDyl/github-actions-pr-gif@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

      - name: Post PR Comment with JavaScript Action from Marketplace
        # Here I have published a JavaScript action to the GitHub Marketplace that does the same thing as the Docker action, but using JavaScript instead of Docker. You can use either one, or both if you want to see the difference in how they work.
        uses: SenuDyl/JS-action-pr-giphy-comment@1.0.0-alpha
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
