name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

# env:
#   MONGO_URI: "mongodb://localhost:27017/solarDB"
#   MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
#   MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    
jobs:
    unit-testing:
        # Start a MongoDB container
        services:
          mongodb:
            image: mongo:6
            ports:
              - 27017:27017

        env:
          # Local MongoDB connection (no username/password)
          MONGO_URI: mongodb://localhost:27017/solarDB

        strategy:
          matrix:
            node-version: [18, 20]
            os: [ubuntu-latest, windows-latest]
            exclude:
              - node-version: 20
                os: windows-latest

        name: Unit Testing
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install Dependencies
          run: npm install

        - name: Wait for MongoDB
          run: |
            until nc -z localhost 27017; do
              echo "Waiting for MongoDB..."
              sleep 1
            done
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml
